require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SkuPatternsController do

  before(:each) do
    @user = FactoryGirl.create(:user)
    sign_in :user, @user
  end

  # This should return the minimal set of attributes required to create a valid
  # SkuPattern. As you add validations to SkuPattern, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    b = FactoryGirl.create(:brand)
    { :pattern => 'some pattern', :brand_id=>b.id }
  end

  describe "GET index" do
    it "assigns all sku_patterns as @sku_patterns" do
      sku_pattern = SkuPattern.create! valid_attributes
      get :index, {}
      assigns(:sku_patterns).should eq([sku_pattern])
    end
  end

  describe "GET show" do
    it "assigns the requested sku_pattern as @sku_pattern" do
      sku_pattern = SkuPattern.create! valid_attributes
      get :show, {:id => sku_pattern.to_param}
      assigns(:sku_pattern).should eq(sku_pattern)
    end
  end

  describe "GET new" do
    it "assigns a new sku_pattern as @sku_pattern" do
      get :new, {}
      assigns(:sku_pattern).should be_a_new(SkuPattern)
    end
  end

  describe "GET edit" do
    it "assigns the requested sku_pattern as @sku_pattern" do
      sku_pattern = SkuPattern.create! valid_attributes
      get :edit, {:id => sku_pattern.to_param}
      assigns(:sku_pattern).should eq(sku_pattern)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SkuPattern" do
        expect {
          post :create, {:sku_pattern => valid_attributes}
        }.to change(SkuPattern, :count).by(1)
      end

      it "assigns a newly created sku_pattern as @sku_pattern" do
        post :create, {:sku_pattern => valid_attributes}
        assigns(:sku_pattern).should be_a(SkuPattern)
        assigns(:sku_pattern).should be_persisted
      end

      it "redirects to the created sku_pattern" do
        post :create, {:sku_pattern => valid_attributes}
        response.should redirect_to(SkuPattern.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved sku_pattern as @sku_pattern" do
        # Trigger the behavior that occurs when invalid params are submitted
        SkuPattern.any_instance.stub(:save).and_return(false)
        post :create, {:sku_pattern => {}}
        assigns(:sku_pattern).should be_a_new(SkuPattern)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SkuPattern.any_instance.stub(:save).and_return(false)
        post :create, {:sku_pattern => {}}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested sku_pattern" do
        sku_pattern = SkuPattern.create! valid_attributes
        # Assuming there are no other sku_patterns in the database, this
        # specifies that the SkuPattern created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SkuPattern.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => sku_pattern.to_param, :sku_pattern => {'these' => 'params'}}
      end

      it "assigns the requested sku_pattern as @sku_pattern" do
        sku_pattern = SkuPattern.create! valid_attributes
        put :update, {:id => sku_pattern.to_param, :sku_pattern => valid_attributes}
        assigns(:sku_pattern).should eq(sku_pattern)
      end

      it "redirects to the sku_pattern" do
        sku_pattern = SkuPattern.create! valid_attributes
        put :update, {:id => sku_pattern.to_param, :sku_pattern => valid_attributes}
        response.should redirect_to(sku_pattern)
      end
    end

    describe "with invalid params" do
      it "assigns the sku_pattern as @sku_pattern" do
        sku_pattern = SkuPattern.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SkuPattern.any_instance.stub(:save).and_return(false)
        put :update, {:id => sku_pattern.to_param, :sku_pattern => {}}
        assigns(:sku_pattern).should eq(sku_pattern)
      end

      it "re-renders the 'edit' template" do
        sku_pattern = SkuPattern.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SkuPattern.any_instance.stub(:save).and_return(false)
        put :update, {:id => sku_pattern.to_param, :sku_pattern => {}}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested sku_pattern" do
      sku_pattern = SkuPattern.create! valid_attributes
      expect {
        delete :destroy, {:id => sku_pattern.to_param}
      }.to change(SkuPattern, :count).by(-1)
    end

    it "redirects to the sku_patterns list" do
      sku_pattern = SkuPattern.create! valid_attributes
      delete :destroy, {:id => sku_pattern.to_param}
      response.should redirect_to(sku_patterns_url)
    end
  end

end
